name: auth_mongo_example
description: An example showcasing authentication with Mongo backend. Implements a simple 'Todo List' use case.
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  jaguar: '>=0.4.3 <0.5.0'
  jaguar_serializer: '>=0.3.4 <0.4.0'
  jaguar_serializer_mongo: '>=0.0.4 <0.1.0'
  jaguar_mongo:
  jaguar_common:
  jaguar_auth:
  jaguar_auth_mongo:
  jaguar_json:
  jaguar_reflect: '>=0.4.6 <0.5.0'

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
