name: server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: teja <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.4.14
  jaguar_serializer: ^2.2.6
  jaguar_serializer_mongo: ^2.2.0
  jaguar_mongo:
  jaguar_common:
  jaguar_auth:
  jaguar_auth_mongo:
  jaguar_reflect:
  jaguar_session_jwt:
  common:
    path: ../common

dev_dependencies:
  test: ^1.0.0
